spring:
  datasource:
    url: jdbc:h2:mem:./trade/target/data
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-client-id
            client-secret: test-client-secret
